spring.application.name=app247
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
server.port=${PORT:8080}
http.client.connect-timeout=${HTTP_CONNECT_TIMEOUT:5s}
http.client.read-timeout=${HTTP_READ_TIMEOUT:15s}
app.test-endpoints.enabled=${TEST_ENDPOINTS_ENABLED:true}
mercado-pago.point.expiration-time=${MP_POINT_EXPIRATION_TIME:PT5M}
api.secret.token=${JWT:senha}

api.mercado.pago.webhook.secret=${MP_WEBHOOK_SECRET:48e4004f27215d5c858ebef031ccfb98aeec92ae395660cc06cbfc105092b750}
api.mercado.pago.test.access.token=${MP_TEST_ACCESS_TOKEN:APP_USR-8964922196078146-072020-9cde0dc37f14b7159b829611044a4810-2703678651}
api.mercado.pago.test.terminal-id=${MP_TEST_TERMINAL_ID:NEWLAND_N950__SBX0000001}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=jefefrs@gmail.com
spring.mail.password=zkoxwppyndbjnnga

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mp.id=2496799661506337
spring.mp.id.secret=lE01h9Vz4QOjEceaA4JCWlbMojSg7ri8
spring.mp.redirect_url=https://tayna-fitful-mariko.ngrok-free.dev/webhook/mercadopago
spring.mp.redirect_url.oauth=https://tayna-fitful-mariko.ngrok-free.dev/mp/oauth/callback

#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
