spring.application.name=app247
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
server.port=${PORT:8080}
api.secret.token=${JWT:senha}
api.mercado.pago.access.token=${ACCESS_TOKEN_MP:token}

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=jefefrs@gmail.com
spring.mail.password=zkoxwppyndbjnnga

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.mp.id=2496799661506337
spring.mp.id.secret=lE01h9Vz4QOjEceaA4JCWlbMojSg7ri8
spring.mp.redirect_url=https://tayna-fitful-mariko.ngrok-free.dev/webhook/mercadopago
spring.mp.redirect_url.oauth=https://tayna-fitful-mariko.ngrok-free.dev/mp/oauth/callback