CREATE TABLE carrinho
(
    carrinho_id CHAR(36) PRIMARY KEY,
    terminal_id VARCHAR(40) NOT NULL,
    status      VARCHAR(30) NOT NULL,
    subtotal    DECIMAL(10, 2),
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);