CREATE TABLE terminal_telemetry_current (
    terminal_id CHAR(36) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    received_at DATETIME(6) NOT NULL,
    operational_status VARCHAR(20) NOT NULL,
    status_reasons VARCHAR(1000) NULL,
    system_uptime_seconds BIGINT NULL,
    cpu_usage_percent DOUBLE NULL,
    cpu_temperature_celsius DOUBLE NULL,
    memory_used_bytes BIGINT NULL,
    memory_total_bytes BIGINT NULL,
    memory_usage_percent DOUBLE NULL,
    disk_used_bytes BIGINT NULL,
    disk_total_bytes BIGINT NULL,
    disk_usage_percent DOUBLE NULL,
    load_average1m DOUBLE NULL,
    undervoltage_now BOOLEAN NULL,
    undervoltage_occurred BOOLEAN NULL,
    throttled_now BOOLEAN NULL,
    throttled_occurred BOOLEAN NULL,
    frequency_capped_now BOOLEAN NULL,
    frequency_capped_occurred BOOLEAN NULL,
    soft_temperature_limit_now BOOLEAN NULL,
    soft_temperature_limit_occurred BOOLEAN NULL,
    throttled_raw VARCHAR(30) NULL,
    network_connected BOOLEAN NULL,
    interface_name VARCHAR(80) NULL,
    wifi_ssid VARCHAR(120) NULL,
    local_ip VARCHAR(45) NULL,
    wifi_signal_percent INT NULL,
    wifi_signal_quality VARCHAR(20) NULL,
    backend_reachable BOOLEAN NULL,
    backend_latency_ms BIGINT NULL,
    app_version VARCHAR(60) NULL,
    app_uptime_seconds BIGINT NULL,
    websocket_status VARCHAR(20) NULL,
    last_product_sync_started_at DATETIME(6) NULL,
    last_product_sync_completed_at DATETIME(6) NULL,
    last_successful_sync_at DATETIME(6) NULL,
    last_sync_error VARCHAR(300) NULL,
    purchase_active BOOLEAN NULL,
    payment_in_progress BOOLEAN NULL,
    display_width INT NULL,
    display_height INT NULL,
    display_orientation VARCHAR(20) NULL,
    PRIMARY KEY (terminal_id),
    CONSTRAINT fk_telemetry_current_terminal FOREIGN KEY (terminal_id) REFERENCES terminal (id)
) ENGINE=InnoDB;

CREATE TABLE terminal_telemetry_history (
    id CHAR(36) NOT NULL,
    terminal_id CHAR(36) NOT NULL,
    captured_at DATETIME(6) NOT NULL,
    received_at DATETIME(6) NOT NULL,
    operational_status VARCHAR(20) NOT NULL,
    system_uptime_seconds BIGINT NULL,
    cpu_usage_percent DOUBLE NULL,
    cpu_temperature_celsius DOUBLE NULL,
    memory_used_bytes BIGINT NULL,
    memory_total_bytes BIGINT NULL,
    memory_usage_percent DOUBLE NULL,
    disk_used_bytes BIGINT NULL,
    disk_total_bytes BIGINT NULL,
    disk_usage_percent DOUBLE NULL,
    load_average1m DOUBLE NULL,
    undervoltage_now BOOLEAN NULL,
    undervoltage_occurred BOOLEAN NULL,
    throttled_now BOOLEAN NULL,
    throttled_occurred BOOLEAN NULL,
    frequency_capped_now BOOLEAN NULL,
    frequency_capped_occurred BOOLEAN NULL,
    soft_temperature_limit_now BOOLEAN NULL,
    soft_temperature_limit_occurred BOOLEAN NULL,
    throttled_raw VARCHAR(30) NULL,
    network_connected BOOLEAN NULL,
    interface_name VARCHAR(80) NULL,
    wifi_ssid VARCHAR(120) NULL,
    local_ip VARCHAR(45) NULL,
    wifi_signal_percent INT NULL,
    wifi_signal_quality VARCHAR(20) NULL,
    backend_reachable BOOLEAN NULL,
    backend_latency_ms BIGINT NULL,
    app_version VARCHAR(60) NULL,
    app_uptime_seconds BIGINT NULL,
    websocket_status VARCHAR(20) NULL,
    last_product_sync_started_at DATETIME(6) NULL,
    last_product_sync_completed_at DATETIME(6) NULL,
    last_successful_sync_at DATETIME(6) NULL,
    last_sync_error VARCHAR(300) NULL,
    purchase_active BOOLEAN NULL,
    payment_in_progress BOOLEAN NULL,
    display_width INT NULL,
    display_height INT NULL,
    display_orientation VARCHAR(20) NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_telemetry_history_terminal FOREIGN KEY (terminal_id) REFERENCES terminal (id)
) ENGINE=InnoDB;

CREATE INDEX idx_telemetry_history_terminal_captured
    ON terminal_telemetry_history (terminal_id, captured_at);

CREATE TABLE terminal_telemetry_alert (
    id CHAR(36) NOT NULL,
    terminal_id CHAR(36) NOT NULL,
    type VARCHAR(40) NOT NULL,
    status VARCHAR(20) NOT NULL,
    message VARCHAR(300) NOT NULL,
    opened_at DATETIME(6) NOT NULL,
    last_observed_at DATETIME(6) NOT NULL,
    resolved_at DATETIME(6) NULL,
    active_key VARCHAR(90) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_telemetry_alert_active UNIQUE (active_key),
    CONSTRAINT fk_telemetry_alert_terminal FOREIGN KEY (terminal_id) REFERENCES terminal (id)
) ENGINE=InnoDB;

CREATE INDEX idx_telemetry_alert_terminal_opened ON terminal_telemetry_alert (terminal_id, opened_at);
CREATE INDEX idx_telemetry_alert_status ON terminal_telemetry_alert (status, last_observed_at);
