package com.jefiro.app247.domain.model.enum_type;

public enum ProdutoCatalogChangeReason {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_ACTIVATED,
    PRODUCT_DEACTIVATED,
    PRODUCT_ASSIGNED_TO_CONDOMINIUM,
    PRODUCT_REMOVED_FROM_CONDOMINIUM,
    PRODUCT_AVAILABILITY_CHANGED,
    PROMOTION_CREATED,
    PROMOTION_UPDATED,
    PROMOTION_STATUS_CHANGED,
    PROMOTION_TIME_TRANSITION
}
