name: Build and Deploy App247

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DOCKERHUB_USERNAME

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build e enviar imagem
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            jefiroo/app247-backend:latest
            jefiroo/app247-backend:${{ github.sha }}

      - name: Configurar SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key
          chmod 600 ~/.ssh/ec2_key
          ssh-keyscan -H "${{ secrets.EC2_HOST }}" >> ~/.ssh/known_hosts

      - name: Verificar chave SSH
        run: |
          echo "Fingerprint da chave usada pelo GitHub:"
          ssh-keygen -y -f ~/.ssh/ec2_key | ssh-keygen -lf -

      - name: Deploy na EC2
        run: |
          ssh -i ~/.ssh/ec2_key \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'

            cd ~/app247

            docker compose pull app
            docker compose up -d --no-deps app

            docker image prune -f
            docker compose ps

          EOF